name: CI/CD with Maven and SSH

on:
  push:
    branches:
      - develop  

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install
        continue-on-error: true 
        id: mvn_build

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 41.216.186.59
          username: bootcampserver
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd Bawaslu-Server
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S git pull origin develop
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S mvn clean install
